spring.application.name=auth-service
server.port=8081
# Mongo Configuration
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=authdb

# Optional (cleaner logs)
spring.data.mongodb.auto-index-creation=true
jwt.secret=ThisIsAVeryStrongSecretKeyForJwtSigning123456
jwt.expiration=3600000