version: "3.8"

services:

  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - app-net
    restart: unless-stopped

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-net
    restart: unless-stopped

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
      - mongo
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/authdb
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
    networks:
      - app-net
    restart: unless-stopped

  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
      - mongo
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/products
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
    networks:
      - app-net
    restart: unless-stopped

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
    networks:
      - app-net
    restart: unless-stopped

  portfolio-frontend:
    build: ./portfolio-frontend
    container_name: portfolio-frontend
    ports:
      - "3000:80"
    networks:
      - app-net
    restart: unless-stopped

networks:
  app-net:

volumes:
  mongo-data: