spring.application.name=product-service
server.port=8082

# MongoDB (local dev)
spring.data.mongodb.uri=mongodb://localhost:27017/products

# Eureka Client (IMPORTANT)
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

# JWT (if used in this service)
jwt.secret=ThisIsAVeryStrongSecretKeyForJwtSigning123456
jwt.expiration=3600000